### ISSUE TITLE
Unsetting NoMobSpawns doesn't work

### ISSUE THREAD

**Issue by zAnonimo** [ShaneBeee/GriefPreventionFlags#110] opened 2020-07-27 16:09 UTC
### Description
Unset flag NoMobSpawns doesn't appear to do anything. I gave to my players permissions to unsetclaim command, and flag NoMobSpawns, they receive the succesful command message, but it doesn't appear to affect the claim mobspawn prevention.

### Steps to Reproduce
Go inside your claim, run command /unsetclaimflag NoMobSpawns

### Expected Behavior
Mob Spawner starts to work, but it doesn't.

### Errors / Screenshots
https://media.discordapp.net/attachments/456210140522348546/737318348760809522/unknown.png (image of one of my players)

Obviously the current light it's because the claim delimitation. They also tried with zero light and no results.

### Server Information
* **Server version/platform:** git-Paper-114
* **GriefPrevention Version:** 16.14.0
* **GriefPreventionFlags Version:** 5.9.1

**Comment by ShaneBeee** [comment] 2020-08-19 03:06
I can not replicate this issue.

Steps I did:
- set global flag via `/setdefaultclaimflag nomobspawns`
- unset in my claim via `/unsetclaimflag nomobspawns`
- spawned a sheep
- placed a spawner

<img width="966" alt="Screen Shot 2020-08-18 at 8 02 20 PM" src="https://user-images.githubusercontent.com/20008482/90587332-f6793b80-e18d-11ea-9b91-dbb4c1e7855c.png">
<img width="966" alt="Screen Shot 2020-08-18 at 8 05 15 PM" src="https://user-images.githubusercontent.com/20008482/90587411-29bbca80-e18e-11ea-86cf-6bb7ab7295cb.png">

**Comment by ShaneBeee** [comment] 2020-10-22 01:26
Closing as I could not reproduce

**Closed by ShaneBeee** 2020-10-22 01:26 UTC
Labels: cannot reproduce
