### ISSUE TITLE
OwnerMemberFly flag with teleport of CMI

### ISSUE THREAD

**Issue by Victor75007** [ShaneBeee/GriefPreventionFlags#128] opened 2020-10-27 07:54 UTC
### Description
 Hello,

I have a child problem.
Child, because i tried it some version of server, from 1.13 to 1.16.3 and not very works.
i use the CMI, as essentials. 
CMI is a premium plugin.

Problem:
I've added the ownerMemberFly to claims as default claim flag.
But when my players join to the server, their keep-spawn locaion is their claims (where is fly) they can't fly.
Thats ok, but if a player use the random teleport in the Wild/world and try go back to the claims but can't fly in.
And the flight kept if the player used the /warp command from own claims.
If the warp target location was an another world, the players can fly in the world, and the flight don't turn off. Never.
So, it a player use the cmi teleport function, (home, tpa, tp, warp, spawn, rtp, back) for go to own claims, the flight no work.
They got a message "flight enabled" but they don't got fly access in their claims.

I haven’t tried the teleport-fly problem with another common plugin like EssentialsX yet.

### Expected Behavior
CMI support.
I have been using the CMI plugin since 2019 and this problem has always existed.

### Errors / Screenshots
No console error.

### Server Information
* **Server version/platform:**            Paper-235 (MC: 1.16.3)
* **GriefPrevention Version:**            16.16.0
* **GriefPreventionFlags Version:**    5.9.3
* **CMI Version**                                8.7.9.3

**Comment by ShaneBeee** [comment] 2020-10-28 07:24
I believe this is a duplicate of #89

**Closed** 2020-11-17 10:29 UTC
Labels: completed, duplicate
